[package]
name = "near-performance-metrics"
version = "0.1.0"
authors = ["Piotr Mikulski <piotr@near.org"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix = "0.9"
futures = "0.3.5"
log = "0.4"
once_cell = "1.5.2"
strum = "0.18"
near-rust-allocator-proxy = { git = "https://github.com/near/near-memory-tracker.git", tag="0.2.4" }
nix = "0.15.0"

tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }

[features]
performance_stats = []
memory_stats = []

[dependencies.bytes]
version = "0.5.0"


[dependencies.bitflags]
version = "1.2"
